### ISSUE TITLE
Doc needs to be updated around the cli command for applying config

### ISSUE THREAD

**Issue by souvmaju-us** [ibm-cloud-docs/databases-for-redis#4]
The documentation needs to be updated around the sample cli snippet. Entered as is (by replacing the redis instance and JSON) it fails.

The name and the JSON needs to be wrapped in single quotes, something like the following:-
`ibmcloud cdb deployment-configuration '<redis-instance-name or crn>' '{"configuration":{"maxmemory-policy":"allkeys-lru","appendonly":"no","stop-writes-on-bgsave-error":"no"}}'`

**Comment by DailyAlice** [comment]
Fixed in the latest commit - https://github.com/ibm-cloud-docs/databases-for-redis/commit/f3ff827ea88312f8df755a6c8a45a4f86c58e74b

Thanks!
