### ISSUE TITLE
ibmcloud cdb deployment-configuration-schema doesn't work as described

### ISSUE THREAD

**Issue by jhenthorn** [ibm-cloud-docs/databases-for-redis#5]
**Description:** There are references to a command line instruction `ibmcloud cdb deployment-configuration-schema` that can be used to view the redis configuration. This command doesn't return the information that is described which makes the "Configuring Redis" section much less helpful.

**Expectation**: Calling `ibmcloud cdb deployment-configuration (NAME|ID)` will return the current configuration settings for the database.

**Actual results:** Calling `Calling ibmcloud cdb deployment-configuration (NAME|ID)` returns a static document describing all the available configuration settings.

```❯ ibmcloud cdb deployment-configuration-schema 'Test'
Retrieving database configuration schema for Test...
OK

Setting                       Default      Kind     Choices                                                                                  Requires Restart
appendonly                    yes          choice   [yes, no]                                                                                false
maxmemory-policy              noeviction   choice   [volatile-lru, allkeys-lru, volatile-random, allkeys-random, volatile-ttl, noeviction]   false
stop-writes-on-bgsave-error   yes          choice   [yes, no]                                                                                false

Setting             Default   Kind      Min/Max     Requires Restart
maxmemory           null      integer   [0, null]   false
maxmemory-samples   5         integer   [0, null]   false
```

Nothing there shows the current configuration of the database
That makes the following statement on the doc page incorrect:

https://cloud.ibm.com/docs/databases-for-redis?topic=databases-for-redis-changing-configuration#using-the-cli

> You can check the current configuration of your deployment through the Cloud Databases cli-plugin with the cdb deployment-configuration-schema command.

It also makes the process of checking the results of reconfiguring the database on the following page really difficult to do. I would expect the reader to do a check of their settings before and after running the change and that is not possible as described

https://cloud.ibm.com/docs/databases-for-redis?topic=databases-for-redis-redis-cache

**Comment by acdntlpoet** [comment]
Doc updates done and in production on Aug 7th. https://cloud.ibm.com/docs/databases-for-redis?topic=databases-for-redis-changing-configuration#using-the-cli
Closing as resolved with clarification of what to expect from the CLI command.
